### ISSUE TITLE
把仓库设为私人仓库是否可以不需要加密操作了

### ISSUE THREAD

**Issue by Wood1314** [li1553770945/NUAA-Check#2]
因为主要的参数信息和Cookie如果设为私人仓库的话其实就没有泄露风险了

**Comment by li1553770945** [comment]
是这个样子的，不过一方面因为我自己要开源，另一方面防止有人不小心忘记设置Private，就设计了这种加密策略。

**Comment by Wood1314** [comment]
好滴了解了～
